version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/usr/app
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  db-data:
